name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and analyze
        env:
          GITHUB_TOKEN: f925c63e-bcad-4512-b3b6-0e508bf0b66b
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=iamneo-production_f925c63e-bcad-4512-b3b6-0e508bf0b66b
          -Dsonar.login=811c9a490983734401ba4e491eaefc8bfa7281de
